#define MAX_RESERVATION_SIZE 256
#define STATE_ACCESS_DELAY_US 500000  // 500ms
#define MAX_JOB_FILE_NAME_SIZE 256
#define MAX_SESSION_COUNT 8
#define MAX_QUEUE_SIZE 256

#define MAX_PIPE_NAME 40


#define NORMAL 4
#define SHUT_DOWN 3
